MM-54314: Return the error correctly from config parse failure
mattermost/mattermost-load-test-ng pull request #649
Opened 2023-09-01 05:39 UTC by agnivade

https://mattermost.atlassian.net/browse/MM-54314

2023-09-05 15:20 UTC, streamer45 approved these changes
Thanks, tested and working nicely :+1:

2023-09-15 16:38 UTC, agarciamontoro requested changes
We seem to test only the case where `path` is empty, and the logic for when that argument is not empty is actually different. I'm looking at the code and most (all?) of the calls pass the value of `--config` or `--comparison-config` flags as `path`, whereas `fallbackPath` is the usual config file relative to the working directory, `./config/whatever`. Should we make the behaviour the same for both? I don't know why it's actually different.
If there's a reason to keep the two paths, we should test them both.

2023-10-10 04:50 UTC, agnivade commented
ping @agarciamontoro

2023-10-10 16:46 UTC, agarciamontoro commented
> And if fallback path exists, then the default values are overriden by the values defined in fallback path.

@agnivade My concern is that we behave differently for `path` and `fallbackpath`, and we're only testing one of the code paths (pun not intended).

2023-10-11 04:36 UTC, agnivade commented
From what I know, that's intentional. @streamer45 - any thoughts on the above?

2023-10-11 22:14 UTC, streamer45 commented
> From what I know, that's intentional. @streamer45 - any thoughts on the above?

I guess you slightly changed the order of operations there. Are we confident that calling `Set()` before attempting to parse from the fallback path isn't going to inadvertently touch fields that may be missing from the JSON file? I'd probably try to keep the sequencing untouched if it's not too complex.

1. Primary path
    - Success: return nil
    - Fail: return error
2. Fallback path
    - Success: return nil
    - Fail: ignore error (Is this case what you weren't totally happy with @agarciamontoro ?)
      - Maybe we could log a global warning just to improve a bit the potential debuggability.
3. Set defaults
    - Success: return nil
    - Fail: return error

2023-10-12 02:52 UTC, agnivade commented
> Are we confident that calling Set() before attempting to parse from the fallback path isn't going to inadvertently touch fields that may be missing from the JSON file? 

I can do that, but I think some tests were failing because of this. If we want to change the functionality, I'm fine with that.

2023-10-12 11:22 UTC, agarciamontoro commented
> Is this case what you weren't totally happy with @agarciamontoro ?)

I'm simply confused with the fact that we behave differently for each of the paths. So I'd love to either:
1. Behave equally for all paths.
2. Maintain the difference in logic, but test all paths.

2023-10-13 06:12 UTC, agnivade commented
Ok, I re-arranged the default setting. Now the default setting happens always, and then all paths are handled equally.

2023-10-13 19:24 UTC, agarciamontoro approved these changes
Much simpler now, thanks!

2023-10-13 19:24 UTC, agarciamontoro commented on defaults/json.go
> +		return fmt.Errorf("failed to read from path %s: %w", fallbackPath, err)
Nit to make the error slightly more useful
```suggestion
		return fmt.Errorf("failed to read from fallback path %s: %w", fallbackPath, err)
```

2023-10-14 03:04 UTC, merged